Repository fjall-rs/lsm-tree, pull requests merged in 2024-12, with the labels that each got.

#86 perf(compaction): Group segment readers in disjoint levels
  src/compaction/worker.rs
  src/range.rs
  src/segment/level_reader.rs
  src/segment/range.rs
Labels: enhancement, performance, refactor

#83 Parallel compactions for Leveled compaction
  src/compaction/fifo.rs
  src/compaction/leveled.rs
  src/compaction/maintenance.rs
  src/compaction/major.rs
  src/compaction/mod.rs
  src/compaction/pulldown.rs
  src/compaction/tiered.rs
  src/compaction/worker.rs
  src/level_manifest/hidden_set.rs
  src/level_manifest/iter.rs
  src/level_manifest/level.rs
  src/level_manifest/mod.rs
  src/memtable/mod.rs
  src/segment/file_offsets.rs
  src/segment/mod.rs
  src/segment/value_block.rs
  src/tree/mod.rs
  tests/tree_recover_counter.rs
Labels: enhancement, epic

#85 better zero copy support from types that implement Into<Slice>
  Cargo.toml
  src/abstract.rs
  src/blob_tree/mod.rs
  src/tree/mod.rs
Labels: enhancement, performance, possibly breaking, api
